@startuml
!pragma layout smetana

class Main{
+ static void main(String[] args)

}

class MediaItem{
- String title
- int releaseYear
- String category
- float rating
- int id
+MediaItem(String title, int year, String category, float rating)

}

class MediaClient{
-TextUI ui
-DBConnector dbc
- MediaMapper mediaMapper
- UserMapper userMapper
-User currentUser;
+MediaClient(User currentUser)
+displayMenu()
+browseMedia()
+sortMediaList(List<MediaItem> mediaOptions)
+displaySortedList(List<MediaItem> mediaOptions)
+buyMedia(List<MediaItem> mediaOptions)
+buyWithWallet(MediaItem selectedMedia, int mediaOption)
+buyWithPunchcard(MediaItem selectedMedia, int mediaOption)
+mediaTypeSelection(MediaItem SelectedMedia, int mediaOption)
+displayPersonalList()
+personalListActions()
+cleanUpPersonalList(User user, int timeLimit)

}


class User{
-String password
-String username
+User(String username, String password)
+boolean equals(Object o)
}


class Movie{

+ Movie(String title, int releaseYear, String category, float rating)
}

class Series{
- int episodes
- int seasons
+Series(String title, int year, String category, float rating, int episodes)
}

class AudioBooks{
- String author
+ AudioBooks(String title, int releaseYear, String category, float rating, String author)
}


class UserClient{
-TextUI ui
-DBConnector dbc
- UserMapper userMapper
-User currentUser
+UserClient(User currentUser)
+loginMenu()
+createUser()
+login()
+addFunds()
+displayAccount()
+deleteAccount()
+buyMembership()
+doesUsernameExist(String username)
}


package "util" {
class TextUI{
- Scanner scanner
+void displayMsg(String s)
+int promptNumeric(String msg)
+String promptText(String msg)
}
}

package "mapper" {
class UserMapper {
- DBConnector DBConnector
+List<User> readUserData()
+saveUserData(User user)
+deleteUserData(User user)
+updateUserBalance(User user, int amount, boolean isWithdrawal)
+int getUserBalance(String username)
+updateUserMembership(User user, int membership)
+int getUserMembership(String username)
+int getUserID(String username)
+addToPersonalList(User user, int ID, String sql)
+List<MediaItem> getPersonalList(User user)

}
class MediaMapper {
- DBConnector DBConnector
- UserMapper userMapper
+List<MediaItem> readMediaData(String sqlQuery)
+getType(String sqlQuery)
}
class DBConnector{
-static final String URL = "jdbc:sqlite:Blogbuster.db"
+Connection connect()
}
}


MediaItem<|--Series
MediaItem <|-- Movie
Main *-- MediaClient
MediaClient *-- "util"
MediaClient -- MediaItem
Main *-- UserClient
UserClient -- User
UserClient *--"util"
UserClient *-- "mapper"
MediaClient *-- "mapper"
MediaItem <|-- AudioBooks

@enduml