@startuml
!pragma layout smetana

class Main{
+ static void main(String[] args)

}

class BlogBuster{
+setup()
}

class MediaItem{
- String title
- int releaseYear
- String category
- float rating
- int id
+MediaItem(String title, int year, String category, float rating, int id)

}

class MediaClient{
-TextUI ui
-DBConnector dbc
- MediaMapper mediaMapper
- UserMapper userMapper
-User currentUser;
+MediaClient(User currentUser)
+void displayMenu()
+void browseMedia()
+List<MediaItem> sortMediaList(List<MediaItem> mediaOptions)
+void displaySortedList(List<MediaItem> mediaOptions)
+void buyMedia(List<MediaItem> sortedMediaOptions, (List<MediaItem> originalMediaOptions))
+void buyWithWallet(MediaItem selectedMedia)
+void buyWithPunchcard(MediaItem selectedMedia)
+void mediaTypeSelection(MediaItem SelectedMedia)
+void displayPersonalList()
+void personalListActions()
+void cleanUpPersonalList(User user, int timeLimit)

}


class User{
-String password
-String username
-String email
+User(String username, String password, String email)
+boolean equals(Object o)
}


class Movie{

+ Movie(String title, int releaseYear, String category, float rating, int id)
}

class Series{
- int episodes
- int seasons
+Series(String title, int year, String category, float rating, int id, int seasons, int episodes)
}

class AudioBooks{
- String author
+ AudioBooks(String title, int releaseYear, String category, float rating, int id, String author)
}


class UserClient{
-TextUI ui
-DBConnector dbc
- UserMapper userMapper
-User currentUser
+UserClient(User currentUser)
+User loginMenu()
+void createUser()
+User login()
+void addFunds()
+void displayAccount()
+void deleteAccount()
+void buyMembership()
+void forgotPassword()
+void changePassword()
+boolean doesUsernameExist(String username)
}


package "util" {
class TextUI{
- Scanner scanner
+void displayMsg(String s)
+int promptNumeric(String msg)
+String promptText(String msg)
}
}

package "mapper" {
class UserMapper {
- DBConnector DBConnector
+List<User> readUserData()
+void saveUserData(User user)
+void deleteUserData(User user)
+void updateUserBalance(User user, int amount, boolean isWithdrawal)
+int getUserBalance(String username)
+void updateUserMembership(User user, int membership)
+int getUserMembership(String username)
+int getUserID(String username)
+void updateUserPunchcard(User user, int amount)
+int getUserPunchcardBalance(String username)
+int getUserId(String username)
+addToPersonalList(User user, int ID, String sql)
+List<MediaItem> getPersonalList(User user)
+String getUserPassword(String username)

}
class MediaMapper {
- DBConnector DBConnector
- UserMapper userMapper
+List<MediaItem> readMediaData(String sqlQuery)
+String getType(String sqlQuery)
}
class DBConnector{
-static final String URL = "jdbc:sqlite:Blogbuster.db"
+Connection connect()
}
}


MediaItem<|--Series
MediaItem <|-- Movie
Main *-- BlogBuster
MediaClient *-- "util"
MediaClient -- MediaItem
BlogBuster *-- UserClient
BlogBuster *-- MediaClient
UserClient -- User
UserClient *--"util"
UserClient *-- "mapper"
MediaClient *-- "mapper"
MediaItem <|-- AudioBooks

@enduml