@startuml
!pragma layout smetana

object MediaClient
object UserClient
object MediaItem
object TextUI
object DBConnector
object Series
object Movie
object AudioBooks
object User




UserClient *-- User
MediaClient *-- MediaItem
UserClient *-- DBConnector
UserClient *-- TextUI
MediaClient *-- DBConnector
MediaClient *-- TextUI

MediaItem <|--"100" Movie
MediaItem <|--"100" Series
MediaItem <|--"50" AudioBooks




@enduml